# Generated by Django 5.0.2 on 2024-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=100)),
                ('description', models.TextField(db_column='description', max_length=1000)),
                ('body', models.CharField(db_column='body', max_length=100)),
                ('characteristics', models.TextField(db_column='characteristics', max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
